### ISSUE TITLE
UI/UX : 페이지 두개 구성

### ISSUE THREAD

**Issue by junarwohn** [HyOsori/Equalizer#11]
하나는 GET의 페이지로, 각 주파수 당 버튼 한개로 총 4개가 필요합니다.
나머지 하나는 SET의 페이지로 현재 이어폰과 맞추려는 이어폰 총 2개를 각각 선택하고 적용을 의미하는 버튼이 필요합니다.

**Comment by kimjieun02** [comment]
SET : 적용 버튼 아래 세부조정을 위한 seekBar 추가
